# Script for build, testing, deploy

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]


jobs:
  build:


    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2  
      env: 
        webhook_url: ${{secrets.DEPLOY_HOOK_URL}}
        webhook_secret: ${{secrets.DEPLOY_HOOK_KEY}}
        
    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}} #this is the github token
        service-id: "srv-cgcmdcm4dad6fr5ll36g?key=-5I-bgMl8Es" #This id is unique for each app
        retries: 20
        wait: 16000
        sleep: 30000